name: ferlokosamnay

services:
  ferlo-kosamnay_angular:
    build:
      context: ferlo-kosamnay_angular
    ports:
      - 4200:4200
    networks:
      - simplon-network

  api_ferlo-kosamnay_laravel:
    build:
      context: api_ferlo-kosamnay_laravel
    ports:
      - 8181:8181
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: api_ferlo-kosamnay_laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - simplon-network

  mysql:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_ferlo-kosamnay_laravel
      MYSQL_PASSWORD: root
    ports:
      - 3306:3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - simplon-network

networks:
  simplon-network:
    driver: bridge

volumes:
  mysql_data: